// Service worker update + stale-version eviction for the PWA.
//
// PROBLEM: even with skipWaiting + clientsClaim in workbox config, an
// already-rendered React app instance keeps running its OLD bundle in
// memory after the new SW takes over. The next route change won't show
// new code because the JS is already loaded. Users have to manually
// reload to get the new code in their tab.
//
// FIX: when virtual:pwa-register's `onNeedRefresh` callback fires (i.e.
// a new SW has installed and is ready to take over), surface a toast
// banner with a "Reload now" button + an auto-reload timer. The default
// auto-reload is 10s — long enough that someone mid-form can dismiss,
// short enough that idle tabs catch up automatically.
//
// Also handles a one-time eviction of any orphaned caches from the
// pre-skipWaiting era so users currently stuck on the old SW recover
// on their first load after this code ships.

import { toast } from "sonner";
import { createScopedLogger } from "@/lib/logger";

const log = createScopedLogger("SWUpdate");

// Local-storage key — set once we've shown the user the prompt for a
// given SW build, so we don't spam if they navigate around before
// reloading.
const PROMPT_DISMISSED_KEY = "motionmax_sw_update_dismissed_at";
const AUTO_RELOAD_DELAY_MS = 10_000;

// Lazily import virtual:pwa-register so non-PWA builds (dev) don't
// blow up when the module is absent.
async function loadRegisterSW() {
  try {
    // The "virtual:pwa-register" module is generated by vite-plugin-pwa
    // at build time. In dev with `devOptions.enabled = false` (default)
    // this throws — handle gracefully so dev sessions don't error.
    const mod = await import("virtual:pwa-register");
    return mod.registerSW as (opts?: {
      immediate?: boolean;
      onNeedRefresh?: () => void;
      onOfflineReady?: () => void;
      onRegistered?: (r: ServiceWorkerRegistration | undefined) => void;
      onRegisterError?: (e: unknown) => void;
    }) => (reloadPage?: boolean) => Promise<void>;
  } catch {
    return null;
  }
}

/**
 * One-time cleanup for users currently on the pre-skipWaiting service
 * worker. Walks `caches.keys()` and unregisters any registration whose
 * scope/script URL doesn't match the current origin's expected SW.
 *
 * Safe to call repeatedly — it's a no-op once nothing matches the
 * "old precache" naming pattern.
 */
async function evictStaleCaches(): Promise<void> {
  if (typeof caches === "undefined") return;
  try {
    const names = await caches.keys();
    // Workbox names look like "workbox-precache-v2-https://...".
    // The most reliable kill: nuke ALL workbox precaches when the
    // module first loads after a deploy. The new SW will rebuild
    // its own precache from the new manifest within seconds.
    const stale = names.filter((n) =>
      n.startsWith("workbox-precache") || n.startsWith("workbox-runtime"),
    );
    if (stale.length === 0) return;
    log.info("Evicting stale caches", { count: stale.length });
    await Promise.all(stale.map((n) => caches.delete(n)));
  } catch (err) {
    log.warn("Stale-cache eviction failed", { err: String(err) });
  }
}

export async function registerServiceWorkerWithUpdates(): Promise<void> {
  // SW only ships in production builds, but the registerSW import is
  // safe to attempt either way (returns null in dev / non-PWA builds).
  const registerSW = await loadRegisterSW();
  if (!registerSW) return;

  const updateSW: (reloadPage?: boolean) => Promise<void> = registerSW({
    // immediate: true — register on first paint, not lazily, so the
    // very first deploy after install gets the SW into the user's tab.
    immediate: true,
    onRegistered(reg) {
      // Periodic update check — the browser does this once an hour by
      // default, but we want users on long-lived tabs (admins watching
      // logs, creators editing big projects) to catch new deploys
      // within minutes. Every 5 minutes is the sweet spot: low overhead,
      // fast enough to feel "live".
      if (reg) {
        setInterval(() => { reg.update().catch(() => {}); }, 5 * 60 * 1000);
      }
    },
    onRegisterError(err) {
      log.warn("SW registration failed", { err: String(err) });
    },
    onNeedRefresh() {
      // A new SW is waiting / activating. We have skipWaiting+clientsClaim
      // so the SW itself takes control immediately; this prompt is about
      // the JS bundle running in the user's tab — that needs a reload to
      // pick up the new code.
      log.info("New version available — prompting user");

      // Don't double-prompt within the same SW build window.
      const lastDismiss = Number(localStorage.getItem(PROMPT_DISMISSED_KEY) || 0);
      if (lastDismiss && Date.now() - lastDismiss < 30_000) {
        log.info("Skipping prompt — recently dismissed");
        return;
      }

      const timerRef: { id: ReturnType<typeof setTimeout> | null } = { id: null };

      const handleReload = () => {
        if (timerRef.id) clearTimeout(timerRef.id);
        // updateSW(true) reloads the page and activates the new SW.
        updateSW(true).catch(() => location.reload());
      };

      const handleDismiss = () => {
        if (timerRef.id) clearTimeout(timerRef.id);
        localStorage.setItem(PROMPT_DISMISSED_KEY, String(Date.now()));
      };

      toast.info("New version of MotionMax is available", {
        description: `Reloading automatically in ${Math.round(AUTO_RELOAD_DELAY_MS / 1000)}s…`,
        duration: AUTO_RELOAD_DELAY_MS + 500,
        action: { label: "Reload now", onClick: handleReload },
        cancel: { label: "Later", onClick: handleDismiss },
        id: "sw-update", // de-dupes if onNeedRefresh fires multiple times
      });

      timerRef.id = setTimeout(handleReload, AUTO_RELOAD_DELAY_MS);
    },
  });

  // Run stale-cache eviction once on boot. This catches users currently
  // on the pre-skipWaiting SW: their old SW was caching a stale
  // app-shell + bundle hash, the new SW (with skipWaiting) replaces it
  // immediately, and this eviction wipes the old precache entries so
  // the next request can't accidentally serve them.
  void evictStaleCaches();
}
