// AUTO-GENERATED by scripts/stripe-create-billing-products.ts
// Do not edit by hand. Re-run the script to regenerate.

export const GENERATED_BILLING_SKUS = {
  "topup_500": {
    "productId": "prod_UT28w12GTWT1Al",
    "priceId": "price_1TU63t6hfVkBDzkSFruU0ldS"
  },
  "topup_2000": {
    "productId": "prod_UT28y5fh1ogOLy",
    "priceId": "price_1TU63u6hfVkBDzkSpQLwDXdJ"
  },
  "topup_10000": {
    "productId": "prod_UT28pGMyspktCC",
    "priceId": "price_1TU63u6hfVkBDzkSaAe1GHD1"
  },
  "topup_50000": {
    "productId": "prod_UT284AbJlfagGw",
    "priceId": "price_1TU63v6hfVkBDzkSdjMVXsR1"
  },
  "pack_addon_creator_monthly": {
    "productId": "prod_UT28o2fK2NGxaH",
    "priceId": "price_1TU63w6hfVkBDzkS4gZyGekN"
  },
  "pack_addon_creator_yearly": {
    "productId": "prod_UT28W0CzLLBP4p",
    "priceId": "price_1TU63x6hfVkBDzkSNL3niLt2"
  },
  "pack_addon_studio_monthly": {
    "productId": "prod_UT28q0F1f7Kr09",
    "priceId": "price_1TU63y6hfVkBDzkSLj7ZyZ2H"
  },
  "pack_addon_studio_yearly": {
    "productId": "prod_UT285c5zLFQ7K5",
    "priceId": "price_1TU63z6hfVkBDzkSC7BwOgbg"
  }
} as const;

export type GeneratedSku = keyof typeof GENERATED_BILLING_SKUS;
