-- ============================================================
-- Add SEO copy column to generations.
-- ============================================================
-- The script-gen LLM now produces a `seo` object alongside `scenes`,
-- containing platform-agnostic copy the user can paste into YouTube /
-- Instagram / TikTok:
--
--   {
--     "title":       "≤70 char headline",
--     "subtitle":    "40–80 char hook/teaser",
--     "description": "150–300 word body (hook → value → CTA)",
--     "hashtags":    ["#one", "#two", "#three", "#four", "#five"]
--   }
--
-- One set per video, written once at generation time. The Inspector's
-- captions tab renders the fields with copy-to-clipboard buttons.
-- Legacy generations created before this column will read NULL and
-- show an "SEO copy not generated yet" empty state.
-- ============================================================

ALTER TABLE public.generations
  ADD COLUMN IF NOT EXISTS seo JSONB DEFAULT NULL;

COMMENT ON COLUMN public.generations.seo IS
  'Platform-agnostic SEO copy generated by the script-gen LLM: {title, subtitle, description, hashtags[5]}. Surfaced in the editor captions tab for copy-paste to YouTube/Instagram/TikTok. Null on legacy rows.';
