-- ============================================================
-- B-NEW-6: Consolidate deletion crons + protect the audit trail
--
-- This migration fixes three coupled GDPR/compliance defects:
--
--   1. Two competing pg_cron jobs each consumed `deletion_requests`
--      rows nightly:
--        • 'process-deletion-requests' @ 02:00 UTC  (LOSER, incomplete)
--          → public.process_deletion_requests()
--          → DELETEs DB rows + auth.users only.
--          → DOES NOT delete storage objects.
--          → DOES NOT enqueue ElevenLabs voice cleanup.
--          → DOES NOT enqueue Stripe customer cleanup.
--        • 'daily-data-retention' @ 03:00 UTC      (CANONICAL, complete)
--          → public.run_data_retention()
--          → public.process_due_deletions()
--             — claims rows with FOR UPDATE SKIP LOCKED
--             — enqueues elevenlabs_voice deletion_tasks
--             — enqueues stripe_cancel deletion_tasks
--             — calls process_deletion_request(id) which purges
--               storage.objects across all user buckets and then
--               deletes auth.users (cascading FKs handle child rows).
--      Because the loser ran first, every deletion_request scheduled
--      to fire on a given day was already 'completed' by 03:00 UTC and
--      the canonical cron found nothing to do — leaving orphaned
--      storage objects, ElevenLabs voices, and Stripe customers on
--      every account deletion. This migration unschedules the loser
--      and stubs its function to a safe no-op.
--
--   2. `deletion_requests.user_id` was declared
--      `REFERENCES auth.users(id) ON DELETE CASCADE`. When the
--      canonical pipeline finally deletes the user, the cascade
--      destroys the very audit row that proves the deletion happened
--      — a GDPR Article 30 (records of processing) violation.
--      This migration drops the cascade FK and recreates it as
--      `ON DELETE SET NULL`. A trigger snapshots the original UUID
--      into `deleted_user_id_snapshot` immediately before the cascade
--      clears `user_id`, so the audit row remains permanently
--      attributable.
--
--   3. The drain-deletion-tasks edge function (running every 15 min
--      via the 'drain-deletion-tasks' cron) consumes the task queue
--      that the canonical pipeline populates. No change required to
--      that path; it is already correct.
--
-- Expected post-migration behavior for a deletion_request whose user
-- has been fully purged:
--    deletion_requests.user_id                 IS NULL
--    deletion_requests.deleted_user_id_snapshot = <original auth.users.id>
--    deletion_requests.status                   = 'completed'
--    deletion_requests row                      persists indefinitely
-- ============================================================


-- ── 1. Add audit-snapshot column ─────────────────────────────

ALTER TABLE public.deletion_requests
  ADD COLUMN IF NOT EXISTS deleted_user_id_snapshot UUID NULL;

COMMENT ON COLUMN public.deletion_requests.deleted_user_id_snapshot IS
  'Snapshot of user_id captured by trigger immediately before the FK '
  'cascade clears user_id on auth.users deletion. GDPR Art. 30 — '
  'preserves attribution of the deletion record after the user is '
  'gone. Populated only at deletion time; NULL while the user still '
  'exists.';

CREATE INDEX IF NOT EXISTS deletion_requests_deleted_snapshot_idx
  ON public.deletion_requests (deleted_user_id_snapshot)
  WHERE deleted_user_id_snapshot IS NOT NULL;


-- ── 2. Snapshot trigger on auth.users delete ─────────────────
-- Fires BEFORE DELETE on auth.users (the only path that triggers
-- the FK cascade) and stamps the about-to-be-cleared user_id into
-- deleted_user_id_snapshot for every deletion_requests row pointing
-- to this user.

CREATE OR REPLACE FUNCTION public.snapshot_deletion_request_user_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  -- Capture the user_id into the snapshot column for any
  -- deletion_requests rows that still reference this user.
  -- This runs BEFORE the FK SET NULL fires, so user_id is still set.
  UPDATE public.deletion_requests
  SET deleted_user_id_snapshot = OLD.id
  WHERE user_id = OLD.id
    AND deleted_user_id_snapshot IS NULL;
  RETURN OLD;
END;
$$;

REVOKE ALL ON FUNCTION public.snapshot_deletion_request_user_id()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS deletion_requests_snapshot_user_id ON auth.users;
CREATE TRIGGER deletion_requests_snapshot_user_id
  BEFORE DELETE ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.snapshot_deletion_request_user_id();


-- ── 3. Replace the cascading FK with ON DELETE SET NULL ──────
-- Find the existing FK constraint name (autogenerated). We drop
-- whatever is currently there and add a fresh, explicit one.

DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'public.deletion_requests'::regclass
    AND contype = 'f'
    AND pg_get_constraintdef(oid) ILIKE '%REFERENCES auth.users%';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.deletion_requests DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

-- Make user_id nullable so SET NULL works.
ALTER TABLE public.deletion_requests
  ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE public.deletion_requests
  ADD CONSTRAINT deletion_requests_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users(id)
    ON DELETE SET NULL;

COMMENT ON CONSTRAINT deletion_requests_user_id_fkey ON public.deletion_requests IS
  'GDPR Art. 30 — audit rows must persist after user deletion. '
  'ON DELETE SET NULL preserves the row; deleted_user_id_snapshot '
  'retains the original UUID for traceability.';


-- ── 4. Disable the loser cron + stub the loser function ──────
-- Unschedule the older 02:00 UTC cron. cron.unschedule errors if the
-- job does not exist, so we guard with a lookup.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'process-deletion-requests'
  ) THEN
    PERFORM cron.unschedule('process-deletion-requests');
    RAISE NOTICE 'Unscheduled cron job process-deletion-requests (loser)';
  END IF;
END $$;

-- Stub the function so any direct caller (manual SQL, legacy job) is
-- harmless. The canonical pipeline is process_due_deletions().
CREATE OR REPLACE FUNCTION public.process_deletion_requests()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  -- DEPRECATED — superseded by public.process_due_deletions()
  -- (scheduled via the 'daily-data-retention' cron) which performs
  -- the full cleanup: storage objects, ElevenLabs voice tasks, Stripe
  -- customer tasks, then auth.users delete with cascade.
  -- Calling this function used to race with the canonical pipeline
  -- and finalize deletion_requests without the external cleanup,
  -- causing orphans on every deletion. It is now a no-op so any
  -- forgotten caller (manual SQL, stale schedule) is harmless.
  RAISE WARNING 'process_deletion_requests() is deprecated — use process_due_deletions(). This call is a no-op.';
END;
$$;

REVOKE ALL ON FUNCTION public.process_deletion_requests() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.process_deletion_requests() TO service_role;

COMMENT ON FUNCTION public.process_deletion_requests() IS
  'DEPRECATED: no-op stub. Use public.process_due_deletions() — '
  'scheduled via the daily-data-retention pg_cron job — which is the '
  'sole canonical path for processing deletion_requests. Kept as a '
  'stub only to neutralize any forgotten direct callers.';


-- ── 5. Verification (informational; no rows changed by this block) ─

-- Sanity-check the constraint:
--   SELECT confdeltype FROM pg_constraint
--   WHERE conname = 'deletion_requests_user_id_fkey';
--   -- Expected: 'n' (SET NULL). Was 'c' (CASCADE) before this migration.

-- Sanity-check cron state:
--   SELECT jobname FROM cron.job
--   WHERE jobname IN ('process-deletion-requests', 'daily-data-retention', 'drain-deletion-tasks');
--   -- Expected: rows for 'daily-data-retention' and 'drain-deletion-tasks' only.
