// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { jwtSessionStorage } from './sessionStorageAdapter';

const ENV_URL = import.meta.env.VITE_SUPABASE_URL;
const ENV_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!ENV_URL) throw new Error("VITE_SUPABASE_URL is required");
if (!ENV_KEY) throw new Error("VITE_SUPABASE_PUBLISHABLE_KEY is required");

export const SUPABASE_URL = ENV_URL;
export const SUPABASE_ANON_KEY = ENV_KEY;
const SUPABASE_PUBLISHABLE_KEY = ENV_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Cipher S-002 / Shield S-001 stopgap: store the Supabase JWT in
// sessionStorage (per-tab, clears on tab close) instead of localStorage.
// See src/integrations/supabase/sessionStorageAdapter.ts for full rationale
// and the migration path to httpOnly cookies via @supabase/ssr.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: jwtSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: { "x-connection-pooler": "supavisor" },
  },
  db: {
    schema: "public",
  },
});